services:
  questdb:
    image: questdb-benchmark:with-data-v5
    container_name: questdb
    ports:
      - "9000:9000"
      - "8812:8812"
      - "9009:9009"
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576

  benchmark:
    image: benchmark-runner:latest
    depends_on:
      - questdb
    environment:
      QUESTDB_HOST: questdb
      QUESTDB_PG_PORT: 8812
      QUESTDB_HTTP_PORT: 9000
      QUESTDB_PORT: 8812

